### ISSUE TITLE
Beni Hatırla - LoginPage15

### ISSUE THREAD

**Issue by Koralp** [KardenTurhan/loginpage#5]
beni hatırla giriş butonu ve şifre unutma yazıları arasında olacak

**Comment by KardenTurhan** [comment]
beni hatırla checkbox ı 
giriş butonu ve şifre unutma linkleri arasına girecektir 
görünümde: önce giriş butonu sonra beni hatırla daha sonra linkler olacaktır

**Comment by Koralp** [comment]
Tamamdır teşekkürler iyi çalışmalar Karden hanım.

**Comment by barancankatesen** [comment]
Beni hatırla butonu için 'şifreni mi unuttun' ile 'şimdi üye ol' başlığı arasında olması gerektiğini söylemiştik
